// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $('.tabs nav a').click(function() {
      $('.tabs pre').hide();
      $('.tabs nav a.active').removeClass('active');
      $(this).addClass('active');
      $("pre." + ($(this).attr('href').substring(1))).show();
      return false;
    });
    return $('nav a').click(function() {
      $.scrollTo("[name=" + ($(this).attr('href').substring(1)) + "]");
      return false;
    });
  });

}).call(this);
