// Generated by CoffeeScript 1.3.3

/*
                     ___
                    /  _0
                    | |
                    | |
^^^^^^^^^^^^^^^^^^^^| |^^^^^^^^^^^^^^
-------------------/   \-------------
   P U B L I C   S U B M A R I N E
*/


(function() {

  window.publicSubmarine = {
    init: function() {
      return this.events = {};
    },
    publish: function(label) {
      var evnt, _i, _len, _ref, _results;
      if (this.events[label]) {
        _ref = this.events[label];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          evnt = _ref[_i];
          _results.push(evnt());
        }
        return _results;
      }
    },
    subscribe: function(label, callback) {
      if (this.events[label]) {
        return this.events[label].push(callback);
      } else {
        return this.events[label] = [callback];
      }
    },
    unsubscribe: function(label, callback) {
      var position;
      if (this.events[label]) {
        position = this.events[label].indexOf(callback);
        if (position !== -1) {
          return this.events[label].splice(position, 1);
        }
      }
    },
    surface: function() {
      return console.log(this.events);
    }
  };

  publicSubmarine.init();

}).call(this);
